language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
script:
  - nosetests
  - pushd examples/00-hello-boost && make && popd
  - pushd examples/01-b2-integration && ./configure && b2 && popd
before_install:
  - wget https://github.com/boostorg/build/releases/download/2014.10/boost-build-2014-10.tar.bz2 -O boost-build-2014-10.tar.bz2
  - tar -xvf boost-build-2014-10.tar.bz2
  - pushd boost-build/ && ./bootstrap.sh && sudo ./b2 install && popd
install: "pip install -r requirements-dev.txt"
