environment:
    matrix:
        - PYTHON: C:\\Python27
        - PYTHON: C:\\Python33
        - PYTHON: C:\\Python34
install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install -r requirements-dev.txt codecov
build: off
test_script:
    - nosetests --with-coverage --cover-package=needy tests/unit
    - nosetests --with-coverage --cover-package=needy tests/functional/generators
    - nosetests --with-coverage --cover-package=needy tests/functional/libraries
    - nosetests --with-coverage --cover-package=needy tests/functional/projects
    - nosetests --with-coverage --cover-package=needy tests/functional/test_development_mode.py
    - nosetests --with-coverage --cover-package=needy tests/functional/test_directory_source.py
    - nosetests --with-coverage --cover-package=needy tests/functional/test_library.py
    - nosetests --with-coverage --cover-package=needy tests/functional/test_needy.py
    - pip install -e .
after_test:
    - codecov
